version: "3.8"

services:
  # Nuxt.js сервер
  dev-horizon-node:
    container_name: dev-horizon-node
    build:
      context: .
    image: dev-horizon-node
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/data/dev.db"
    volumes:
      - ./prisma:/data
    depends_on:
      - db

  # SQLite база данных
  db:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - ./prisma:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
