services:
  dev-horizon-node:
    container_name: dev-horizon-node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dev-horizon-node
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: "mysql://user:password@db/devhorizon" # Обновите учетные данные
    depends_on:
      - db
    networks:
      - app-network

  bot:
    container_name: dev-horizon-bot
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: dev-horizon-bot
    restart: always
    environment:
      BOT_TOKEN: "7696869877:AAHYLtyjbqbSSjhWrFBVLeLMis6kWtwaIK8" # Укажите токен вашего бота
      DATABASE_URL: "mysql://user:password@db/devhorizon" # Подключение к MySQL
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: dev-horizon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devhorizon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
