version: "3.9"

services:
  app:
    container_name: dev-horizon-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: "file:/app/prisma/dev.db"
    volumes:
      - ./prisma:/app/prisma
    depends_on:
      - db
    restart: always

  db:
    image: nouchka/sqlite3
    container_name: dev-horizon-db
    volumes:
      - ./prisma:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
